# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\amather\thinIceLabs\thinX\ui_thinX.ui'
#
# Created: Thu Mar 27 13:39:41 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 350)
        MainWindow.setMinimumSize(QtCore.QSize(600, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Glyphicons/icons/glyphicons_001_leaf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textLog = QtWidgets.QTextEdit(self.centralwidget)
        self.textLog.setEnabled(True)
        self.textLog.setAutoFillBackground(False)
        self.textLog.setReadOnly(True)
        self.textLog.setObjectName("textLog")
        self.horizontalLayout.addWidget(self.textLog)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuUtilities = QtWidgets.QMenu(self.menubar)
        self.menuUtilities.setObjectName("menuUtilities")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Glyphicons/icons/glyphicons_144_folder_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Glyphicons/icons/glyphicons_063_power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.actionUnits = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Glyphicons/icons/glyphicons_023_magnet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnits.setIcon(icon3)
        self.actionUnits.setObjectName("actionUnits")
        self.actionContexts = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Glyphicons/icons/glyphicons_413_posterous_spaces.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContexts.setIcon(icon4)
        self.actionContexts.setObjectName("actionContexts")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Glyphicons/icons/glyphicons_064_lightbulb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon5)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCalculations = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Glyphicons/icons/glyphicons_041_charts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCalculations.setIcon(icon6)
        self.actionCalculations.setObjectName("actionCalculations")
        self.actionLabels = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Glyphicons/icons/glyphicons_115_text_smaller.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLabels.setIcon(icon7)
        self.actionLabels.setObjectName("actionLabels")
        self.actionConcepts = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Glyphicons/icons/glyphicons_196_circle_exclamation_mark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConcepts.setIcon(icon8)
        self.actionConcepts.setObjectName("actionConcepts")
        self.actionConsolidateLabels = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Glyphicons/icons/glyphicons_100_font.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConsolidateLabels.setIcon(icon9)
        self.actionConsolidateLabels.setObjectName("actionConsolidateLabels")
        self.actionMerrillBridgePrep = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Glyphicons/icons/glyphicons_026_road.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMerrillBridgePrep.setIcon(icon10)
        self.actionMerrillBridgePrep.setObjectName("actionMerrillBridgePrep")
        self.actionMerrillBridgeSort = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Glyphicons/icons/glyphicons_080_retweet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMerrillBridgeSort.setIcon(icon11)
        self.actionMerrillBridgeSort.setObjectName("actionMerrillBridgeSort")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuUtilities.addAction(self.actionConcepts)
        self.menuUtilities.addAction(self.actionLabels)
        self.menuUtilities.addAction(self.actionConsolidateLabels)
        self.menuUtilities.addAction(self.actionCalculations)
        self.menuUtilities.addAction(self.actionContexts)
        self.menuUtilities.addAction(self.actionUnits)
        self.menuUtilities.addAction(self.actionMerrillBridgeSort)
        self.menuUtilities.addAction(self.actionMerrillBridgePrep)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuUtilities.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConcepts)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLabels)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConsolidateLabels)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCalculations)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionContexts)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUnits)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMerrillBridgeSort)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMerrillBridgePrep)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "thinX"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuUtilities.setTitle(_translate("MainWindow", "Utilities"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open Instance Document"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionUnits.setText(_translate("MainWindow", "Comply with UTR"))
        self.actionContexts.setText(_translate("MainWindow", "Remove Unused Contexts"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionCalculations.setText(_translate("MainWindow", "Find Duplicate Calculations"))
        self.actionLabels.setText(_translate("MainWindow", "Remove Unused Labels"))
        self.actionLabels.setToolTip(_translate("MainWindow", "Remove Unused Labels"))
        self.actionConcepts.setText(_translate("MainWindow", "Remove Unused Extension Concepts"))
        self.actionConcepts.setToolTip(_translate("MainWindow", "Remove Unused Extension Concepts"))
        self.actionConsolidateLabels.setText(_translate("MainWindow", "Consolidate Labels"))
        self.actionMerrillBridgePrep.setText(_translate("MainWindow", "Merrill Bridge Prep"))
        self.actionMerrillBridgeSort.setText(_translate("MainWindow", "Merrill Bridge Sort"))
        self.actionMerrillBridgeSort.setToolTip(_translate("MainWindow", "Merrill Bridge Sort"))

import icons_rc
